stevotvr_groupsub_main:
    path: /groupsub/subs/{name}
    defaults: { _controller: stevotvr.groupsub.controller.main:handle, name: null }

stevotvr_groupsub_ppjs:
    path: /groupsub/ppjs/{action}
    defaults: { _controller: stevotvr.groupsub.controller.ppjs:handle }
